version: 2
updates:
  # Root package.json (Husky, lint-staged)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    reviewers:
      - "jackdamnielzz"
    assignees:
      - "jackdamnielzz"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"

  # Web app package.json (Next.js, React, etc.)
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 10
    reviewers:
      - "jackdamnielzz"
    assignees:
      - "jackdamnielzz"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "web"
      - "automated"
    # Group related updates together
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
      next-ecosystem:
        patterns:
          - "next*"
          - "@next/*"
      eslint-ecosystem:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "@typescript-eslint/*"
      firebase-ecosystem:
        patterns:
          - "firebase*"
          - "@firebase/*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    reviewers:
      - "jackdamnielzz"
    assignees:
      - "jackdamnielzz"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"